# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [ ]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [ ]:
a = pd.Series([100, 200, 300, 400])

Print a, and data type

In [ ]:
print(a)
print(a.dtype)

0    100
1    200
2    300
3    400
dtype: int64
int64

Using indexing access the element 300 from the series a.

In [ ]:
print(a[2])

300

What are the values of index for series a?

In [ ]:
print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [ ]:
a.index = ['c', 'a', 'b', 'd']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [ ]:
print(a['d'])

400

Sort the values wrt to the index and print it

In [ ]:
print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [ ]:
b = pd.Series([800, 450, 100], index=['e', 'f', 'g'])
print(b)

e    800
f    450
g    100
dtype: int64

Append b series at the end of a series

In [ ]:
# The .append() method was removed in pandas 2.0.
# Use pd.concat() instead to combine Series.
a = pd.concat([a, b])

In [ ]:
print(a)

c    100
a    200
b    300
d    400
e    800
f    450
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [ ]:
a_sorted = a.sort_values(ascending=False)
print(a_sorted.index)

Index(['e', 'f', 'd', 'b', 'a', 'c', 'g'], dtype='object')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [ ]:
df = pd.DataFrame(a, columns=['points'])
display(df)

   points
c     100
a     200
b     300
d     400
e     800
f     450
g     100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [ ]:
print(df.shape)
# It implies there are 7 rows and 1 column.

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [ ]:
print(df.index)
print("Is it same as series a?", df.index.equals(a.index))

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='object')
Is it same as series a? True

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [ ]:
print('Head:')
display(df.head())
print('\nTail:')
display(df.tail())
# Head represents the first n rows (default 5), Tail represents the last n rows.

Head:

   points
c     100
a     200
b     300
d     400
e     800

Tail:

   points
b     300
d     400
e     800
f     450
g     100

Rename the column of the dataframe as 'points'

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [ ]:
fruits_list = np.random.choice(['orange','mango','apple'], size=7)
print(fruits_list)

['mango' 'mango' 'apple' 'mango' 'apple' 'apple' 'orange']

In [ ]:
fruits = pd.Series(fruits_list)
print(fruits)

0     mango
1     mango
2     apple
3     mango
4     apple
5     apple
6    orange
dtype: object

Change the index of fruits to the index of dataframe df

In [ ]:
fruits.index = df.index
print(fruits)

c     mango
a     mango
b     apple
d     mango
e     apple
f     apple
g    orange
dtype: object

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [ ]:
df['fruits'] = fruits
display(df.head())

   points fruits
c     100  mango
a     200  mango
b     300  apple
d     400  mango
e     800  apple

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [ ]:
d1 = pd.DataFrame({
    'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
    'Temperature': [15, 22, 20, 26, -2]
})

Print(d1)

In [ ]:
print(d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [ ]:
print(d1.shape)

(5, 2)

Set city = d1['city']

In [ ]:
city = d1['city']

print city <br>
What is the type of city.

In [ ]:
print(city)
print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: object
<class 'pandas.core.series.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [ ]:
d2 = pd.DataFrame({
    'city': ['Bengalaru', 'Coimbatore', 'Srirangam', 'Pondicherry'],
    'Temperature': [24, 35, 36, 39]
})
print(d2)

          city  Temperature
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

print the shape of this dataframe

In [ ]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [ ]:
d3 = pd.concat([d1, d2], ignore_index=True)
display(d3)

          city  Temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
5    Bengalaru           24
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

In [ ]:
cold_cities = d3[d3['Temperature'] <= 20]
display(cold_cities)
print('Count:', len(cold_cities))

         city  Temperature
0  Chandigarh           15
2      Kanpur           20
4      Manali           -2

Count: 3

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [ ]:
hot_cities = d3[d3['Temperature'] >= 35]
display(hot_cities)

          city  Temperature
6   Coimbatore           35
7    Srirangam           36
8  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not.
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [ ]:
def is_ut(x):
    uts = ['Chandigarh', 'Pondicherry', 'Delhi']
    return x in uts

d3['is_ut'] = d3['city'].apply(is_ut)
print(d3)

          city  Temperature  is_ut
0   Chandigarh           15   True
1        Delhi           22   True
2       Kanpur           20  False
3      Chennai           26  False
4       Manali           -2  False
5    Bengalaru           24  False
6   Coimbatore           35  False
7    Srirangam           36  False
8  Pondicherry           39   True

In [ ]:
# print d3

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT -
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [ ]:
def c_to_f(c):
    return (c * 9/5) + 32

In [ ]:
print(c_to_f(10))

50.0

In [ ]:
d3['temp_farenhiet'] = d3['Temperature'].apply(c_to_f)
display(d3)

          city  Temperature  is_ut  temp_farenhiet
0   Chandigarh           15   True            59.0
1        Delhi           22   True            71.6
2       Kanpur           20  False            68.0
3      Chennai           26  False            78.8
4       Manali           -2  False            28.4
5    Bengalaru           24  False            75.2
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [ ]:
ut_cities_d1 = d1[d1['city'].isin(['Chandigarh', 'Delhi', 'Pondicherry'])]
display(ut_cities_d1)

         city  Temperature
0  Chandigarh           15
1       Delhi           22

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [ ]:
# Filtering d3 for temperatures > 90 Farenhiet as calculated in previous steps
hot_f_cities = d3[d3['temp_farenhiet'] > 90]
display(hot_f_cities)

          city  Temperature  is_ut  temp_farenhiet
6   Coimbatore           35  False            95.0
7    Srirangam           36  False            96.8
8  Pondicherry           39   True           102.2

Select only the first three rows of the dataframe d1.

In [ ]:
display(d1.iloc[:3])

         city  Temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20

Select all the rows and last two columns in the dataframe.

In [ ]:
display(d3.iloc[:, -2:])

   is_ut  temp_farenhiet
0   True            59.0
1   True            71.6
2  False            68.0
3  False            78.8
4  False            28.4
5  False            75.2
6  False            95.0
7  False            96.8
8   True           102.2

## Groupby

In [ ]:
# Create a dataframe using dictionary of your choice

# data =

In [ ]:
# Create a dataframe using dictionary of your choice
data = {
    'Category': ['Electronics', 'Furniture', 'Electronics', 'Furniture', 'Electronics', 'Appliances', 'Appliances'],
    'Sub-Category': ['Phones', 'Chairs', 'Laptops', 'Tables', 'Phones', 'Ovens', 'Microwaves'],
    'Sales': [1200, 800, 2500, 1500, 1100, 400, 300],
    'Quantity': [5, 2, 3, 4, 6, 1, 2]
}

df_group = pd.DataFrame(data)
display(df_group)

      Category Sub-Category  Sales  Quantity
0  Electronics       Phones   1200         5
1    Furniture       Chairs    800         2
2  Electronics      Laptops   2500         3
3    Furniture       Tables   1500         4
4  Electronics       Phones   1100         6
5   Appliances        Ovens    400         1
6   Appliances   Microwaves    300         2

In [ ]:
# Use Groupby of single column with aggregate sum()

In [ ]:
# Use Groupby of single column with aggregate sum()
grouped_sum = df_group.groupby('Category')['Sales'].sum()
print(grouped_sum)

Category
Appliances      700
Electronics    4800
Furniture      2300
Name: Sales, dtype: int64

In [ ]:
# Use Groupby of single column with aggregate count()

In [ ]:
# Use Groupby of single column with aggregate count()
grouped_count = df_group.groupby('Category')['Quantity'].count()
print(grouped_count)

Category
Appliances     2
Electronics    3
Furniture      2
Name: Quantity, dtype: int64

In [ ]:
grouped_min_max = df_group.groupby('Category')['Sales'].agg(['min', 'max'])
display(grouped_min_max)

              min   max
Category
Appliances    300   400
Electronics  1100  2500
Furniture     800  1500

In [ ]:
# Use Groupby of single column with aggregate min() and max()
grouped_min_max = df_group.groupby('Category')['Sales'].agg(['min', 'max'])
print(grouped_min_max)

              min   max
Category
Appliances    300   400
Electronics  1100  2500
Furniture     800  1500

In [ ]:
grouped_mean_multi = df_group.groupby(['Category', 'Sub-Category'])['Sales'].mean()
display(grouped_mean_multi)

Category     Sub-Category
Appliances   Microwaves       300.0
             Ovens            400.0
Electronics  Laptops         2500.0
             Phones          1150.0
Furniture    Chairs           800.0
             Tables          1500.0
Name: Sales, dtype: float64

In [ ]:
# Use Groupby of any 2 columns with aggregate mean()
grouped_mean_multi = df_group.groupby(['Category', 'Sub-Category'])['Sales'].mean()
print(grouped_mean_multi)

Category     Sub-Category
Appliances   Microwaves       300.0
             Ovens            400.0
Electronics  Laptops         2500.0
             Phones          1150.0
Furniture    Chairs           800.0
             Tables          1500.0
Name: Sales, dtype: float64

In [ ]:
grouped_min_max_multi = df_group.groupby(['Category', 'Sub-Category'])['Sales'].agg(['min', 'max'])
display(grouped_min_max_multi)

                           min   max
Category    Sub-Category
Appliances  Microwaves     300   300
            Ovens          400   400
Electronics Laptops       2500  2500
            Phones        1100  1200
Furniture   Chairs         800   800
            Tables        1500  1500

In [ ]:
# Use Groupby of any 2 columns with aggregate min() and max()
grouped_min_max_multi = df_group.groupby(['Category', 'Sub-Category'])['Sales'].agg(['min', 'max'])
print(grouped_min_max_multi)

                           min   max
Category    Sub-Category
Appliances  Microwaves     300   300
            Ovens          400   400
Electronics Laptops       2500  2500
            Phones        1100  1200
Furniture   Chairs         800   800
            Tables        1500  1500

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [ ]:
a_dates = pd.date_range(start='2020-01-01', end='2021-04-01')
print(a_dates)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

print a

In [ ]:
print(a_dates)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[ns]', length=457, freq='D')

What is the len of a?

In [ ]:
print(len(a_dates))

457

What is the type of a?

In [ ]:
print(type(a_dates))

<class 'pandas.core.indexes.datetimes.DatetimeIndex'>